

DECLARE
  P_FROMCITY VARCHAR2(16);
  P_TOCITY VARCHAR2(16);
  P_STARTDATE DATE;
  P_ENDDATE DATE;
  P_ORDERBY NUMBER;
  P_FLIGHTLIST ORINDADEMO.SIMPLE_EXAMPLES.flights_refcursor_type;
  
  p_bool boolean := TRUE;
  
   P_AIRLINE_LISTING ORINDADEMO.SIMPLE_EXAMPLES.airline_refcursor_type;
  P_AIRPORT_LISTING ORINDADEMO.SIMPLE_EXAMPLES.airport_refcursor_type;
  P_AIRCRAFT_LISTING ORINDADEMO.SIMPLE_EXAMPLES.aircraft_refcursor_type;



BEGIN
  P_FROMCITY := 'SFO';
  P_TOCITY := 'JFK';
  P_STARTDATE := sysdate;
  P_ENDDATE := sysdate;
  P_ORDERBY := 1;
  


  SIMPLE_EXAMPLES.DIRECT_FLIGHT_AVAILABLE(
    P_FROMCITY => P_FROMCITY,
    P_TOCITY => P_TOCITY,
   p_direct => p_bool
  );
  
  SIMPLE_EXAMPLES.FIND_DIRECT_FLIGHTS(
    P_FROMCITY => P_FROMCITY,
    P_TOCITY => P_TOCITY,
    P_STARTDATE => P_STARTDATE,
    P_ENDDATE => P_ENDDATE,
    P_ORDERBY => P_ORDERBY,
    P_FLIGHTLIST => P_FLIGHTLIST
  );
  
   P_ORDERBY := 2;

 SIMPLE_EXAMPLES.FIND_DIRECT_FLIGHTS(
    P_FROMCITY => P_FROMCITY,
    P_TOCITY => P_TOCITY,
    P_STARTDATE => P_STARTDATE,
    P_ENDDATE => P_ENDDATE,
    P_ORDERBY => P_ORDERBY,
    P_FLIGHTLIST => P_FLIGHTLIST
  );
 P_ORDERBY := 3;
 
 SIMPLE_EXAMPLES.FIND_DIRECT_FLIGHTS(
    P_FROMCITY => P_FROMCITY,
    P_TOCITY => P_TOCITY,
    P_STARTDATE => P_STARTDATE,
    P_ENDDATE => P_ENDDATE,
    P_ORDERBY => P_ORDERBY,
    P_FLIGHTLIST => P_FLIGHTLIST
  );


  SIMPLE_EXAMPLES.GETLISTS(
    P_AIRLINE_LISTING => P_AIRLINE_LISTING,
    P_AIRPORT_LISTING => P_AIRPORT_LISTING,
    P_AIRCRAFT_LISTING => P_AIRCRAFT_LISTING
  );
  
  
END;