//
//
  CREATE TABLE "ORINDADEMO"."AIRCRAFT" 
   (	"AIRCRAFT_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "ACT_PK" PRIMARY KEY ("AIRCRAFT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
//

CREATE TABLE AIRCRAFT
(AIRCRAFT_TYPE VARCHAR(50) NOT NULL
, CONSTRAINT ACT_PK PRIMARY KEY 
(AIRCRAFT_TYPE)
);
