//
//
  CREATE TABLE "ORINDADEMO"."AIRPORTS" 
   (	"AIRPORT_CODE" VARCHAR2(16) NOT NULL ENABLE, 
	"AIRPORT_NAME" VARCHAR2(80), 
	 CONSTRAINT "APT_PK" PRIMARY KEY ("AIRPORT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
//

CREATE TABLE AIRPORTS
(AIRPORT_CODE VARCHAR(16) NOT NULL
,AIRPORT_NAME VARCHAR(80)
, CONSTRAINT APT_PK PRIMARY KEY 
(AIRPORT_CODE)
);
