//
//
  CREATE TABLE "ORINDADEMO"."BOOKINGS" 
   (	"CUSTOMER_NAME" VARCHAR2(12) NOT NULL ENABLE, 
	"AIRLINE_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"FLIGHT_NUMBER" NUMBER NOT NULL ENABLE, 
	"DEPARTURE_TIME" DATE NOT NULL ENABLE, 
	"SEAT" VARCHAR2(3), 
	 CONSTRAINT "BKG_PK" PRIMARY KEY ("CUSTOMER_NAME", "AIRLINE_NAME", "FLIGHT_NUMBER", "DEPARTURE_TIME", "SEAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "BKG_CST" FOREIGN KEY ("CUSTOMER_NAME")
	  REFERENCES "ORINDADEMO"."CUSTOMERS" ("NAME") ENABLE, 
	 CONSTRAINT "BKG_FLT" FOREIGN KEY ("AIRLINE_NAME", "FLIGHT_NUMBER", "DEPARTURE_TIME")
	  REFERENCES "ORINDADEMO"."FLIGHTS" ("AIRLINE_NAME", "FLIGHT_NUMBER", "DEPARTURE_TIME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
//

CREATE TABLE BOOKINGS
(CUSTOMER_NAME VARCHAR(12) NOT NULL
,AIRLINE_NAME VARCHAR(50) NOT NULL
,FLIGHT_NUMBER BIGINT NOT NULL
,DEPARTURE_TIME TIMESTAMP NOT NULL
,SEAT VARCHAR(3) NOT NULL
, CONSTRAINT BKG_PK PRIMARY KEY 
(CUSTOMER_NAME,AIRLINE_NAME,FLIGHT_NUMBER,DEPARTURE_TIME,SEAT)
);
