//
//
  CREATE TABLE "ORINDADEMO"."CUSTOMERS" 
   (	"NAME" VARCHAR2(80) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(50), 
	"CITY" VARCHAR2(50), 
	"STATE" VARCHAR2(2), 
	"ZIP" NUMBER(5,0), 
	"BIRTHDATE" DATE, 
	"PHONE" VARCHAR2(12), 
	 CONSTRAINT "CST_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
//

CREATE TABLE CUSTOMERS
(NAME VARCHAR(80) NOT NULL
,ADDRESS VARCHAR(50)
,CITY VARCHAR(50)
,STATE VARCHAR(2)
,ZIP DECIMAL
,BIRTHDATE TIMESTAMP
,PHONE VARCHAR(12)
, CONSTRAINT CST_PK PRIMARY KEY 
(NAME)
);
