//
//
  CREATE TABLE "ORINDADEMO"."FLIGHTS" 
   (	"DEPARTURE_CITY" VARCHAR2(16) NOT NULL ENABLE, 
	"ARRIVAL_CITY" VARCHAR2(16) NOT NULL ENABLE, 
	"AIRLINE_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"FLIGHT_NUMBER" NUMBER NOT NULL ENABLE, 
	"DEPARTURE_TIME" DATE NOT NULL ENABLE, 
	"ARRIVAL_TIME" DATE NOT NULL ENABLE, 
	"AIRCRAFT_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "FLT_PK" PRIMARY KEY ("AIRLINE_NAME", "FLIGHT_NUMBER", "DEPARTURE_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FLT_DEP_CITY" FOREIGN KEY ("DEPARTURE_CITY")
	  REFERENCES "ORINDADEMO"."AIRPORTS" ("AIRPORT_CODE") ENABLE, 
	 CONSTRAINT "FLT_ARR_CITY" FOREIGN KEY ("ARRIVAL_CITY")
	  REFERENCES "ORINDADEMO"."AIRPORTS" ("AIRPORT_CODE") ENABLE, 
	 CONSTRAINT "FLT_AIRLINE" FOREIGN KEY ("AIRLINE_NAME")
	  REFERENCES "ORINDADEMO"."AIRLINES" ("AIRLINE_NAME") ENABLE, 
	 CONSTRAINT "FLT_AIRCRAFT" FOREIGN KEY ("AIRCRAFT_TYPE")
	  REFERENCES "ORINDADEMO"."AIRCRAFT" ("AIRCRAFT_TYPE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
//

CREATE TABLE FLIGHTS
(DEPARTURE_CITY VARCHAR(16) NOT NULL
,ARRIVAL_CITY VARCHAR(16) NOT NULL
,AIRLINE_NAME VARCHAR(50) NOT NULL
,FLIGHT_NUMBER BIGINT NOT NULL
,DEPARTURE_TIME TIMESTAMP NOT NULL
,ARRIVAL_TIME TIMESTAMP NOT NULL
,AIRCRAFT_TYPE VARCHAR(50) NOT NULL
, CONSTRAINT FLT_PK PRIMARY KEY 
(AIRLINE_NAME,FLIGHT_NUMBER,DEPARTURE_TIME)
);
